### ISSUE TITLE
Avoid page refresh/dealy when liked or disliked

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#661]
There is a delay/page refresh once like or dislike is clicked. We want to avoid it to improve the experience.

![2024-05-29_18-14-47](https://github.com/Esri/solutions-components/assets/3836616/2d1deb31-11a6-4b4d-8276-2c27d9c5910f)

**Comment by sumitzarkar** [comment]
@skrishn 

- Once like or dislike button is clicked we have multiple operations running 
    - apply edits on the layer to update the data
    - update local storage
    - Refresh the feature details to show the updated like and dislike field values

These operations are async requests and we need to wait till all these actions are completed hence we have added the loading indicator.

**Comment by chris-fox** [comment]
@sumitzarkar, I understand why it is happening, can we just assume the that when liking or disliking it is a pretty simple operation and 99.9% of the time it will be successfully and just increment the count synchronously, so there is no page reload/refresh. If it fails after the async request we could do a refresh of the UI to set the state due to the error?

**Comment by sumitzarkar** [comment]
@chris-fox 

The only issue with this is if in the popup details the like/dislike field is shown then to reflect the new updated values we have to refresh the entire details.
If we are not concerned about the updation of the like/dislike field values in feature details we can avoid the loading indicator and do other tasks in the background like you mentioned

**Comment by chris-fox** [comment]
yea, let's do that. I don't have a use case for wanting the like/dislike fields in the feature details. We can wait to see if we get customer requests for refreshing the details after a like/dislike.

**Comment by sumitzarkar** [comment]
@chris-fox 

We have one more way to show loading indicator as we are using calcite-buttons, this will avoid user clicking same button multiple time when the operation is in progress
![reporter661](https://github.com/Esri/solutions-components/assets/9443956/e7cbf182-9486-4651-9f88-23d47dd65c55)

**Comment by chris-fox** [comment]
@sumitzarkar, that looks good.

**Comment by chris-fox** [comment]
I am seeing the new loading icon next to the like/dislike buttons but I still see the entire feature details panel reload after the like/dislike action completes.

**Comment by skrishn** [comment]
Yes, I see the same. @sumitzarkar can we fix this feature panel loading?

**Comment by sumitzarkar** [comment]
@chris-fox @skrishn 

>I am seeing the new loading icon next to the like/dislike buttons but I still see the entire feature details panel reload after the like/dislike action completes.

- As discussed we can reproduce this only with arcade elements in the popup details.
- We have removed the logic to refresh the attributes in info card

 _Note: The only drawback would be if a like or dislike field is added in popup details those will not reflect the updates when like/dislike is updated._

We have fixed this and will deliver it in the next code drop

**Comment by skrishn** [comment]
@sumitzarkar I see the numbers jumping after hitting like/dislike

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=54fe3738157d4775b8ff9794c34f58ff

[screen-recorder-tue-jun-11-2024-15-12-57.webm](https://github.com/Esri/solutions-components/assets/3836616/e27d6255-81fe-44d9-92a1-325ef36c34ec)

**Comment by sumitzarkar** [comment]
@skrishn 
>I see the numbers jumping after hitting like/dislike

We don't have control over this. We see this behavior as we are showing the button's loading indicator and updating the button's lable

**Comment by skrishn** [comment]
@sumitzarkar I'm still seeing this on QA too. As I mentioned in the call, I see this behavior after the recent code drop. Please look to see if there is a way to avoid the number sliding to the left as the loading indicator updates the value.

**Comment by chris-fox** [comment]
@skrishn, this is the default behavior of the calcite button when you set the loading property to true. This was to prevent the user from rapidly clicking the like or dislike button before we could apply the edits to the feature service.

https://developers.arcgis.com/calcite-design-system/components/button/

I guess an alternative would be to disable the buttons until the edit is applied. In this way they wouldn't show the loading icon, but would grey out until the edit was complete. This might be a weird user experience though.

**Comment by sumitzarkar** [comment]
@skrishn @chris-fox 

Please confirm if any changes requried in this

**Comment by skrishn** [comment]
@sumitzarkar No action is required at this point. We can consider the alternative from Chris based on user feedback.
